### ISSUE TITLE
Update existing values in the database with appropriate resolution

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/y-video-back-end#168]
Once #161 is corrected, the existing values in the database should be updated. About 70 contents affected by this bug have `Censor` annotations, so the fix should be accompanied by an email alerting instructors that blur positions may have been moved. (Look for `blurs_affected_by_aspect_ratio_bug.csv` on my laptop for this list)

_Originally posted by @reynoldsnlp in https://github.com/BYU-ODH/y-video-back-end/issues/161#issuecomment-1760313810_

**Comment by reynoldsnlp** [comment]
@WorldsEndless did you already do this? If so, I need a list of contents (and their owners) that have blurs in `annotations` so that we can let them double-check that changing the aspect ratio didn't move their blurs to the wrong parts of the screen.
