### ISSUE TITLE
 My user is still being updated on `yvideodev`

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/y-video-back-end#79]
My `account_name` was changed to `rjr45 no_name` and my `account_type` was changed to `4`. There are several other users in the database with `account_type` `4`, which should be impossible.

**Comment by esdraszx** [comment]
I have a working version local. But I need to make sure it works on development. It is not in production yet

**Comment by esdraszx** [comment]
Version in dev and local. There were no new complains after the fix. Closing issue
