### ISSUE TITLE
production gives `500` when trying to get `collections`

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/y-video-back-end#80]
Should contain the key `:copyrighted`. The database does have this field, so there is some disconnect. We tried restarting the server and that did not fix the problem.

```-- Spec failed -------------------- ({:archived false, :expired-content (), :content ({:description "stuff", :tags "", :allow-captions true, :collection-id #uuid "a88ddef7-6873-4f96-ba29-ee74554066d8", :words "", :resource-id #uuid "25836252-333f-43f6-952e-b50fcf3ae1dd", :allow-definitions true, :title "Batman begins", :thumbnail "empty", :id #uuid "79c7bc2a-691d-46e6-b308-60b71fd249b7", :file-version "English", :url "", :clips "", :content-type "video", :annotations "{\"type\":\"Censor\",\"icon\":\"/static/media/event_censor.ae402e36.svg\",\"start\":13.538355609346858,\"end\":23.53835560934686,\"layer\":0,\"position\":{\"3.7\":[0,0,30,40]}}; ", :published true, :allow-notes true, :views 0}), :public false, :id #uuid "a88ddef7-6873-4f96-ba29-ee74554066d8", :collection-name "HLC Prime", :owner #uuid "cd488b0f-0cf3-4fe1-9187-cea317bb4ab9", :published true} ... ...) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ should contain key: :copyrighted | key | spec | |==============+===================================================| | :copyrighted | | -- Spec failed -------------------- (... {:archived false, :expired-content (), :content (), :public false, :id #uuid "efad28ba-d62a-4cbb-89c4-c401b1a76310", :collection-name "Marie-Laure", :owner #uuid "79e53e27-cb0b-4d6d-b157-8d5dba04cb4f", :published true} ...) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ should contain key: :copyrighted | key | spec | |==============+===================================================| | :copyrighted | | -- Spec failed -------------------- (... ... {:archived false, :expired-content (), :content ({:description "Stuff from another thing", :tags "", :allow-captions true, :collection-id #uuid "e91cca11-8072-4ea8-85c7-330ff4dc15f6", :words "", :resource-id #uuid "99008dae-ee61-43fd-9fe8-98dabc9996cb", :allow-definitions true, :title "KLIOS", :thumbnail "empty", :id #uuid "4d07cbc4-53df-4e03-be92-b67c11ee3820", :file-version "Russian", :url "", :clips "", :content-type "video", :annotations "", :published true, :allow-notes true, :views 0}), :public false, :id #uuid "e91cca11-8072-4ea8-85c7-330ff4dc15f6", :collection-name "test", :owner #uuid "79e53e27-cb0b-4d6d-b157-8d5dba04cb4f", :published false}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ should contain key: :copyrighted | key | spec | |==============+===================================================| | :copyrighted | | ------------------------- Detected 3 errors```

**Comment by reynoldsnlp** [comment]
@esdraszx did you do something to fix this? I'm not getting a `500` anymore.

**Comment by esdraszx** [comment]
Yes rob I fixed it. I had to update the views in the database since the query looks at the view and not the actual table.
