### ISSUE TITLE
deleted user handle

### ISSUE THREAD

**Issue by saejong-jang-by** [BYU-ODH/y-video-back-end#86]
- when the deleted user logs into our system, the backend has to delete the timestamp (set it as a null) in DB instead of creating a new account.

**Comment by esdraszx** [comment]
@reynoldsnlp what did we say about this do you remember? Wouldn't this defeat the purpose of deleting a user? 

If a user was deleted and wants to login again should we have a options for a request? If a user is deleted it must have been for an important reason and they should not be allowed in the system unless proper aproval is given.

Let me know what you think

**Comment by reynoldsnlp** [comment]
I'm not sure that this will ever be an issue. Y-video collections and resources are so sandboxed that I'm not sure how a bad actor could cause problems for other users.

**Comment by esdraszx** [comment]
show an error message to contact admin
